Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox"

    config.vm.define :wordpress do |wordpress|
        wordpress.vm.box = "ubuntu/bionic64"

        wordpress.vm.network "private_network", ip: "192.168.50.20"

        wordpress.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get install puppet -y"
        
        wordpress.vm.provision "puppet" do |puppet|
            puppet.manifest_file = "wordpress.pp"
        end
    end
end