Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    #Configure VM ip address
    #config.vm.network "public_network", ip: "192.168.1.8"

    # Port forwarding to mysql
    #config.vm.network "forwarded_port", guest: 3306, host: 8888

    config.vm.provider "virtualbox" do |v|
        v.name = "cursos"

        v.memory = 4096
        v.cpus = 1
      end
    
    #installing ubuntu desktop in order to have GUI
    config.vm.provision "shell", inline: 'sudo apt update -y'

    # Install mysql-server
    #config.vm.provision "shell", inline: 'sudo apt-get install mysql-server -y'

  end