Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/impish64"

    #Configure VM ip address
    #config.vm.network "private_network", ip: "192.168.1.8"

    config.vm.provider "virtualbox" do |v|
        v.name = "teste_"
        v.gui = true

        #enable virtualization
        v.customize ["modifyvm", :id, "--hwvirtex", "on"]
        v.customize ["modifyvm", :id, "--nestedpaging", "on"]
        v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]

        v.memory = 8192
        v.cpus = 2
      end
    
    #installing ubuntu desktop in order to have GUI
    config.vm.provision "shell", inline: 'sudo apt update -y'
    config.vm.provision "shell", inline: 'sudo apt upgrade -y'
    config.vm.provision "shell", inline: 'sudo apt install ubuntu-desktop -y'

    #install default-jdk
    config.vm.provision "shell", inline: 'sudo apt install default-jdk -y'

    #set JAVA_HOME
    config.vm.provision "shell", inline: 'echo "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/">>~/.bashrc'
    config.vm.provision "shell", inline: 'echo "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/">>~/.profile'

    #installing android studio latest version available
    config.vm.provision "shell", inline: 'sudo snap install android-studio --classic'

    #setting android environment variables
    config.vm.provision "shell", inline: 'sudo echo "export ANDROID_HOME=$HOME/Android/Sdk">>~/.bashrc'
    config.vm.provision "shell", inline: 'sudo echo "export ANDROID_HOME=$HOME/Android/Sdk">>~/.profile'
    config.vm.provision "shell", inline: 'sudo echo "export PATH=$PATH:$ANDROID_HOME/emulator">>~/.bashrc'
    config.vm.provision "shell", inline: 'sudo echo "export PATH=$PATH:$ANDROID_HOME/emulator">>~/.profile'
    config.vm.provision "shell", inline: 'sudo echo "export PATH=$PATH:$ANDROID_HOME/tools">>~/.bashrc'
    config.vm.provision "shell", inline: 'sudo echo "export PATH=$PATH:$ANDROID_HOME/tools">>~/.profile'
    config.vm.provision "shell", inline: 'sudo echo "export PATH=$PATH:$ANDROID_HOME/tools/bin">>~/.bashrc'
    config.vm.provision "shell", inline: 'sudo echo "export PATH=$PATH:$ANDROID_HOME/tools/bin">>~/.profile'
    config.vm.provision "shell", inline: 'sudo echo "export PATH=$PATH:$ANDROID_HOME/platform-tools">>~/.bashrc'
    config.vm.provision "shell", inline: 'sudo echo "export PATH=$PATH:$ANDROID_HOME/platform-tools">>~/.profile'

    #install react-native
    config.vm.provision "shell", inline: 'sudo apt-get install nodejs -y'
    config.vm.provision "shell", inline: 'sudo apt-get install npm -y'
    config.vm.provision "shell", inline: 'sudo npm install -g yarn'
    config.vm.provision "shell", inline: 'sudo npm install -g npx'
    config.vm.provision "shell", inline: 'sudo npm install -g react-native-cli'

  end